=== wawanco/m2id-xml-project/project/order.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT order (idCustomer, idCompany, currency, cart)>
<!ATTLIST order
	id CDATA #REQUIRED
>
<!ELEMENT idCompany (#PCDATA)>
<!ELEMENT idCheck   (#PCDATA)>
<!ELEMENT currency  EMPTY>
<!ATTLIST currency type (euros|dollars) "euros">
<!ELEMENT cart (item)+>
<!ELEMENT item (product, quantity)>
<!ELEMENT product (name, unitPrice)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT unitPrice (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>

=== wawanco/m2id-xml-project/project/order.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="order.xsl"?>
<!DOCTYPE orderList SYSTEM "order.dtd" >
<order id="1">
	<idCustomer>1</idCustomer>
	<idCompany>1</idCompany>
	<currency type="euros"/>
	<cart>
		<item>
				<product>
					<name>burger</name>
					<unitPrice>4</unitPrice>
				</product>
				<quantity>2</quantity>
		</item>
		<item>
				<product>
					<name>drink</name>
					<unitPrice>1</unitPrice>
				</product>
				<quantity>3</quantity>
		</item>
	</cart>
</order>
