=== wawanco/m2id-xml-project/project/order-list.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT orderList (order)*>
<!ELEMENT order (id, customer,company)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT customer (identite?, idCustomer, idBank?, cart)>
<!ELEMENT identite EMPTY>
<!ATTLIST identite 
	name      CDATA #REQUIRED 
	firstname CDATA #REQUIRED
>
<!ELEMENT idCustomer (#PCDATA)>
<!ELEMENT idBank (#PCDATA)>
<!ELEMENT cart (product)+>
<!ELEMENT product (id, name, unitPrice, currency)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT unitPrice (#PCDATA)>
<!ELEMENT currency EMPTY>
<!ATTLIST currency type (euros|dollars) "euros">
<!ELEMENT company (id, name, idBank)>

=== wawanco/m2id-xml-project/project/order-list.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="order.xsl"?>
<!DOCTYPE orderList SYSTEM "order-list.dtd" >
<orderList>
	<order>
		<id>1</id>
		<customer>
			<idCustomer>1</idCustomer>
			<cart>
				<product>
					<id>0</id>
					<name>burger</name>
					<unitPrice>4</unitPrice>
					<currency type="dollars" />
				</product>
				<product>
					<id>0</id>
					<name>fries</name>
					<unitPrice>1.5</unitPrice>
					<currency type="dollars" />
				</product>
				<product>
					<id>0</id>
					<name>drink</name>
					<unitPrice>1</unitPrice>
					<currency type="dollars" />
				</product>
			</cart>
		</customer>
		<company>
			<id>0</id>
			<name>McDonalds</name>
			<idBank>0</idBank>
		</company>
	</order>
	<order>
		<id>2</id>
		<customer>
			<idCustomer>2</idCustomer>
			<cart>
				<product>
					<id>2</id>
					<name>Athens</name>
					<unitPrice>499</unitPrice>
					<currency type="euros" />
				</product>
			</cart>
		</customer>
		<company>
			<id>2</id>
			<name>TravelAir</name>
			<idBank>1</idBank>
		</company>
	</order>
	<order>
		<id>3</id>
		<customer>
			<idCustomer>3</idCustomer>
			<cart>
				<product>
					<id>2</id>
					<name>Barcelone</name>
					<unitPrice>899</unitPrice>
					<currency type="euros" />
				</product>
				<product>
					<id>2</id>
					<name>Barcelone</name>
					<unitPrice>899</unitPrice>
					<currency type="euros" />
				</product>
			</cart>
		</customer>
		<company>
			<id>2</id>
			<name>TravelAir</name>
			<idBank>1</idBank>
		</company>
	</order>
</orderList>
